apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: '{{.Release.Name}}-api-healthcheck'
  namespace: {{.Release.Namespace}}
  labels: {{- include "joyna.selectorLabels" . | nindent 4}}
spec:
  targetRef:
    group: ''
    kind: Service
    name: {{include "joyna.apiServiceName" .}}
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        port: {{.Values.api.port}}
        requestPath: /ready
