apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-configmap'
  namespace: {{.Release.Namespace}}
  labels: {{- include "joyna.selectorLabels" . | nindent 4}}
data:
  APP_ENV: {{.Values.api.env | quote}}
  APP_PORT: {{.Values.api.port | quote}}
  POSTGRES_USER: {{.Values.postgres.user}}
  POSTGRES_DB: {{.Values.postgres.database}}
