apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: '{{.Release.Name}}-gw'
  namespace: {{.Release.Namespace}}
  labels: {{- include "joyna.selectorLabels" . | nindent 4}}
spec:
  gatewayClassName: gke-l7-regional-external-managed
  addresses:
    - type: NamedAddress
      value: '{{.Values.gateway.staticIPName}}'
  listeners:
    - protocol: HTTP
      port: 80
      name: '{{.Release.Name}}-gw-http'
      hostname: '{{.Values.gateway.hostname}}'
      allowedRoutes:
        namespaces:
          from: Same
    - protocol: HTTPS
      port: 443
      name: '{{.Release.Name}}-gw-https'
      hostname: '{{.Values.gateway.hostname}}'
      tls:
        mode: Terminate
        options:
          networking.gke.io/cert-manager-certs: '{{.Values.gateway.certName}}'
      allowedRoutes:
        namespaces:
          from: Same
