apiVersion: v1
kind: Secret
metadata:
  name: '{{.Release.Name}}-secrets'
  namespace: {{.Values.namespace}}
  labels: {{- include "joyna.selectorLabels" . | nindent 4}}
  annotations:
    'helm.sh/hook': pre-install,pre-upgrade
    'helm.sh/hook-weight': '-10'
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{.Values.postgres.password}}
  DATABASE_URL: 'postgres://{{.Values.postgres.user}}:{{.Values.postgres.password}}@{{include "joyna.postgresServiceName" .}}:{{.Values.postgres.port}}/{{.Values.postgres.database}}?sslmode=disable'
