FROM golang:1.27.1-alpine3.24 AS builder

WORKDIR /app

COPY go.mod go.sum* ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/notifier ./cmd/notifier

FROM alpine:3.24

RUN addgroup -S app && adduser -S app -G app

WORKDIR /app

COPY --from=builder /bin/notifier .

USER app

ENTRYPOINT ["./notifier"]
