apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: api-healthcheck
  namespace: joyna
spec:
  targetRef:
    group: ""
    kind: Service
    name: api
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /ready
