name: Build & Push API to Artifact Registry

on:
  workflow_call:
    inputs:
      gh_env:
        required: true
        type: string
      imageName:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      context:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.gh_env }}
      deployment: false
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v7

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        id: auth
        with:
          token_format: 'access_token'
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_GH_SERVICE_ACCOUNT }}

      - name: Login to Google Artifact Repository
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.GCP_ARTIFACTS_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push Container
        run: |-
          REPO=${{ vars.GCP_ARTIFACTS_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/joyna
          TAG="$(git rev-parse --short HEAD)"
          docker build -f "${{ inputs.dockerfile }}" -t "${REPO}/${{ inputs.imageName }}:${TAG}" "${{ inputs.context }}"
          docker push "${REPO}/${{ inputs.imageName }}:${TAG}"
